engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODO
ratings:
  paths:
  - "**.php"
exclude_paths:
  - vendor/

