language: php

php:
  - '5.5'
  - '5.6'

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - php ./vendor/bin/codacycoverage clover ./build/logs/clover.xml 
